# Generated by Django 3.1 on 2020-08-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstzy',
            name='File',
            field=models.FileField(upload_to='File/FirstZY/orignal'),
        ),
    ]
