# Generated by Django 3.1 on 2020-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deal', '0004_auto_20200831_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='original_file',
            old_name='file_name',
            new_name='kl_name',
        ),
        migrations.AddField(
            model_name='original_file',
            name='pc_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='original_file',
            name='syd_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firstzy',
            name='File',
            field=models.FileField(upload_to='File/FirstZY/original'),
        ),
    ]
