# Generated by Django 3.1 on 2020-09-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deal', '0006_auto_20200904_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstzy',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='firstzy',
            name='File',
            field=models.FileField(upload_to=''),
        ),
    ]
