# Generated by Django 3.1 on 2020-09-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deal', '0008_auto_20200905_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_file',
            name='t_tddxx',
            field=models.FileField(default=1, upload_to='File/original/t_tddxx'),
            preserve_default=False,
        ),
    ]
