# Generated by Django 3.1 on 2020-09-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deal', '0009_original_file_t_tddxx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_file',
            name='File',
            field=models.FileField(upload_to='File/original/TDD'),
        ),
    ]
