# Generated by Django 3.1.1 on 2020-09-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deal', '0011_original_file_clean_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstzy',
            name='Dealed_File',
            field=models.FileField(default=1, upload_to='File/FirstZY/result/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='original_file',
            name='cleaned_file',
            field=models.FileField(default=1, upload_to='File/original/result'),
            preserve_default=False,
        ),
    ]
