# Generated by Django 3.1.1 on 2020-09-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deal', '0012_auto_20200911_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstzy',
            name='Dealed_File',
        ),
        migrations.AlterField(
            model_name='original_file',
            name='clean_message',
            field=models.CharField(default='数据未清洗', max_length=50),
        ),
        migrations.AlterField(
            model_name='original_file',
            name='cleaned_file',
            field=models.FilePathField(),
        ),
    ]
