# Generated by Django 3.1.1 on 2020-09-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deal', '0015_auto_20200913_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_file',
            name='cleaned_file',
            field=models.FileField(upload_to='File\\data_clean'),
        ),
    ]
