# Generated by Django 3.1.1 on 2020-09-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deal', '0017_remove_original_file_cleaned_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Today_CleanedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Path', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('message', models.CharField(default='请先完成所有分省清洗', max_length=50)),
            ],
        ),
    ]
