# Generated by Django 3.1.1 on 2020-09-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deal', '0018_today_cleanedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today_cleanedfile',
            name='Date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='today_cleanedfile',
            name='Path',
            field=models.CharField(default='数据未清洗', max_length=100),
        ),
        migrations.AlterField(
            model_name='today_cleanedfile',
            name='name',
            field=models.CharField(default='数据未清洗', max_length=100),
        ),
    ]
