# Generated by Django 3.1.1 on 2020-09-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deal', '0019_auto_20200914_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_file',
            name='Rename_FilePath',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
