# Generated by Django 3.1.1 on 2020-09-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_deal', '0020_original_file_rename_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='original_file',
            name='cleaned_FilePath',
        ),
    ]
