# Generated by Django 3.1.1 on 2020-09-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deal', '0021_remove_original_file_cleaned_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Today_MergedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='当日数据拼接', max_length=100)),
                ('Path', models.CharField(default='', max_length=100)),
                ('Date', models.CharField(max_length=20)),
                ('message', models.CharField(default='请正确上传源文件', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='today_cleanedfile',
            name='Path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='today_cleanedfile',
            name='name',
            field=models.CharField(default='数据清洗汇总', max_length=100),
        ),
    ]
